[package]
name = "wurmple"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
derive_setters = "0.1.6"
egui = "0.31.1"
egui-winit = "0.31.1"
env_logger = "0.11.6"
log = "0.4.26"
muda = "0.16.1"
vk-mem = "0.4.0"
winit = "0.30.9"
